import { Scale, Trophy, CheckCircle2 } from "lucide-react";

import Card from "../common/Card";
import SectionTitle from "../common/SectionTitle";
import WinnerBadge from "./WinnerBadge";

export default function JudgeCard({ judge }) {
  const winner =
    judge.solution_1_score >= judge.solution_2_score
      ? "Mistral AI"
      : "Cohere AI";

  return (
    <Card>
      <SectionTitle
        title="Judge Recommendation"
        subtitle="Evaluation generated by Gemini"
      />

      <div className="mt-8 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-indigo-100">
            <Scale size={26} className="text-indigo-600" />
          </div>

          <div>
            <h3 className="text-lg font-semibold">AI Judge</h3>

            <p className="text-sm text-slate-500">Gemini Evaluation</p>
          </div>
        </div>

        <WinnerBadge winner={winner} />
      </div>

      <div className="mt-10 grid grid-cols-2 gap-8">
        {/* Solution 1 */}

        <div className="rounded-2xl border border-slate-200 p-6">
          <div className="mb-5 flex items-center justify-between">
            <h4 className="font-semibold">Mistral AI</h4>

            <span className="font-bold text-indigo-600">
              {judge.solution_1_score}/10
            </span>
          </div>

          <div className="flex items-start gap-3">
            <CheckCircle2 size={18} className="mt-1 text-green-600" />

            <p className="text-slate-600 leading-7">
              {judge.solution_1_reasoning}
            </p>
          </div>
        </div>

        {/* Solution 2 */}

        <div className="rounded-2xl border border-slate-200 p-6">
          <div className="mb-5 flex items-center justify-between">
            <h4 className="font-semibold">Cohere AI</h4>

            <span className="font-bold text-indigo-600">
              {judge.solution_2_score}/10
            </span>
          </div>

          <div className="flex items-start gap-3">
            <CheckCircle2 size={18} className="mt-1 text-green-600" />

            <p className="text-slate-600 leading-7">
              {judge.solution_2_reasoning}
            </p>
          </div>
        </div>
      </div>
    </Card>
  );
}
