import { HumanMessage } from "@langchain/core/messages";
import {
  StateSchema,
  MessagesValue,
  ReducedValue,
  StateGraph,
  START,
  END,
  type GraphNode,
  CompiledStateGraph,
} from "@langchain/langgraph";
import { z } from "zod";
import { cohereModel, googleModel, mistralModel } from "./models.ai.js";
import { createAgent, providerStrategy } from "langchain";

// const State = new StateSchema({
//   messages: MessagesValue,
//   solution_1: new ReducedValue(z.string().default(""), {
//     reducer: (current, next) => {
//       return next;
//     },
//   }),
//   solution_2: new ReducedValue(z.string().default(""), {
//     reducer: (current, next) => {
//       return next;
//     },
//   }),
//   // judge_recommendations: new ReducedValue(
//   //   z.object().default({
//   //     solution_1_score: 0,
//   //     solution_2_score: 0,
//   //   }),
//   //   {
//   //     reducer: (current, next) => {
//   //       return next;
//   //     },
//   //   },
//   // ),
//   judge_recommendations: new ReducedValue(
//     z
//       .object({
//         solution_1_score: z.number(),
//         solution_2_score: z.number(),
//       })
//       .default({
//         solution_1_score: 0,
//         solution_2_score: 0,
//       }),
//     {
//       reducer: (_, next) => next,
//     },
//   ),
// });

const state = new StateSchema({
  problem: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_reasoning: z.string().default(""),
    solution_2_reasoning: z.string().default(""),
  }),
});

const solutionNode: GraphNode<typeof state> = async (state) => {
  // console.log(state);

  const [mistral_response, cohere_response] = await Promise.all([
    mistralModel.invoke(state.problem),
    cohereModel.invoke(state.problem),
  ]);

  return {
    solution_1: mistral_response.text,
    solution_2: cohere_response.text,
  };
};

// const judgeNode: GraphNode<typeof state> = async (state) => {
//   // console.log("Invoking judge", state);

//   const { solution_1, solution_2 } = state;

//   const judge = createAgent({
//     model: googleModel,
//     tools: [],
//     responseFormat: providerStrategy(
//       z.object({
//         solution_1_score: z.number().min(0).max(10),
//         solution_2_score: z.number().min(0).max(10),
//       }),
//     ),
//   });

//   const judgeResponse = await judge.invoke({
//     messages: [
//       new HumanMessage(
//         `You are a judge with evaluating the quality of two solutions to a problem. The problem is ${state.messages[0].text}. The first solution is: ${solution_1}. The second solution is: ${solution_2}. Please provide a score between 0 and 10 for each solution, where 0 means the solution is completely incorrect or irrelevant, and 10 means the solution is perfect and fully address the problem.`,
//       ),
//     ],
//   });

//   // console.dir(judgeResponse, { depth: null });

//   const result = judgeResponse.structuredResponse;

//   // console.log("Structured Response:", result);

//   return {
//     judge_recommendations: result,
//   };
// };

const judgeNode: GraphNode<typeof state> = async (state) => {
  const { problem, solution_1, solution_2 } = state;

  const judge = createAgent({
    model: googleModel,
    responseFormat: providerStrategy(
      z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_reasoning: z.string(),
        solution_2_reasoning: z.string(),
      }),
    ),
    systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with the reasoning for the scores.`,
  });

  const judgeResponse = await judge.invoke({
    messages: [
      new HumanMessage(`
        Problem: ${problem}
        Solution 1: ${solution_1}
        Solution 2: ${solution_2}
        Please evaluate the solutions and provide scores and reasoning.
        `),
    ],
  });

  const {
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning,
  } = judgeResponse.structuredResponse;

  return {
    judge: {
      solution_1_score,
      solution_2_score,
      solution_1_reasoning,
      solution_2_reasoning,
    },
  };
};

const graph = new StateGraph(state)
  .addNode("solution", solutionNode)
  .addNode("judge_node", judgeNode)
  .addEdge(START, "solution")
  .addEdge("solution", "judge_node")
  .addEdge("judge_node", END)
  .compile();

// export default async function name(userMessage: string) {
//   const result = await graph.invoke({
//     messages: [new HumanMessage(userMessage)],
//   });

//   console.log(result);
//   return result.messages;
// }

export const runGraph = async (problem: string) => {
  const result = await graph.invoke({
    problem: problem,
  });

  return result;
};
