import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";

import MainLayout from "../components/layout/MainLayout";
import BattleCard from "../components/battle/BattleCard";
import BattleLoading from "../components/battle/BattleLoading";
import useBattle from "../hooks/useBattle";

// Replace this with your real API call later
// import { getBattleById } from "../services/battle.service";

export default function BattlePage() {
  const { id } = useParams();

  const { battle, fetchBattle, loading } = useBattle();

  useEffect(() => {
    fetchBattle(id);
  }, [id]);
  return (
    <MainLayout>
      <div className="mx-auto max-w-7xl px-8 py-10">
        <div className="mb-10">
          <h1 className="text-4xl font-bold">Battle Details</h1>

          <p className="mt-2 text-slate-500">
            Compare responses generated by multiple AI models.
          </p>
        </div>

        {loading ? (
          <BattleLoading
            battle={{
              status: "generating_models",
            }}
          />
        ) : (
          <BattleCard battle={battle} />
        )}
      </div>
    </MainLayout>
  );
}
